# Generated by Django 3.2.6 on 2021-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.CharField(default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter',
            field=models.CharField(default='#', max_length=100, verbose_name='Twitter'),
        ),
    ]
